
services:
    doc_pages.admin.doc_page:
        class: Unlooped\DocPagesBundle\Admin\DocPageAdmin
        arguments: [~, Unlooped\DocPagesBundle\Entity\DocPage, DocPagesBundle:DocPageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Help Pages", label: "Pages" }
        public: true
