<?php

namespace Unlooped\DocPagesBundle\Repository;

/**
 * DocPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocPageRepository extends \Doctrine\ORM\EntityRepository
{
}
